server:
  servlet:
     context-path: /agent
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pg.kkworld.com:5432/kkworld?prepareThreshold=0
    username: kkworld
    password: kkworld2015

mybatis:
  mapper-locations: classpath:mapping/*.xml
agent:
  promotionUrl: http://mobile.kktalkee.com/register#/index?channel=

